#!/bin/bash -x

# mauck
#
# faux-mock using docker containers
#
# Copyright 2018 Jason Burrell

SRPM="$1"
RPMBUILD="rpmbuild --define \"_rpmdir $MAUCK_RESULTS\" --define \"_srcrpmdir $MAUCK_RESULTS/SRPMS\" "

if [ $# -ne 1 ];
then
    echo "$0: ERROR: usage: $0 package.{src.rpm,tar...}" >&2
    exit 1
fi

# input file sanity check
for STYLE in "-r" "-t";
do
    ## ask rpmbuild to check the input file
    rpmbuild ${STYLE}s --nobuild "$1" &> /dev/null
    if [ $? -eq 0 ];
    then
	BUILD_ALL="${STYLE}a"
	if [ "$STYLE" = "-t" ];
	then
	    # we need to build the srpm first for builddep
	    RPMB_OUTPUT=$(su --login "${MAUCK_USER}" /bin/sh -c "$RPMBUILD -ts \"$SRPM\"")
	    SRPM="${RPMB_OUTPUT#*: }"
	fi
	break
    fi
done

# load up the build dependencies
dnf --assumeyes builddep "$SRPM"

# drop privs
su --login "${MAUCK_USER}" /bin/sh -c "$RPMBUILD $BUILD_ALL \"$1\""
